### ISSUE TITLE
Discords への移行について

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/meeting#11]
## issue purpose
- [Slack 初の料金改定とフリープランの内容変更のお知らせ](https://slack.com/intl/ja-jp/blog/news/pricing-and-plan-updates) に伴い、[Discord](https://discord.com/)  へ移行するかを議論

## Close conditions
- [ ] 移行するかの可否

**Comment by dynamis** [comment]
discord 移転はしないという話だったので wontfix close
