### ISSUE TITLE
チュートリアルサイトのパーツ画像変換バグ確認

### ISSUE THREAD

**Issue by gurezo** [chirimen-oh/meeting#4]
## issue purpose
    - パーツリストページを qiita に陳腐化する前提で記載 bot化？（週1アップデート）
        - ちなみに、実体配線図用のfritzingパーツもかな～り充実してるよ～
    - twitter bot 
        - パーツリストページへのリンク誘導 @gurezo
        - チュートリアルページへのリンク誘導 @gurezo
        - 実体配線図用のfritzingパーツポスト
        - 逆引きリスト情報
    - zenn 掲載は、次回アジェンダにする。
    - SEO対策したほうが、早い？

## Close conditions
- [ ] something....
- [ ] something....

**Comment by gurezo** [comment]
定期ボットは、一旦休み

**Comment by kou029w** [comment]
> - 実体配線図用のfritzingパーツポスト

GitHub CHIRIMEN org内にある .fzz ファイルの検索: https://github.com/search?q=org%3Achirimen-oh+extension%3Afzz&type=code

**Comment by kou029w** [comment]
対応表

カテゴリ |   |   |   | /partslist/ | /examples/ | /pizero/esm-examples/
-- | -- | -- | -- | -- | -- | --
I2C センサ | 温度センサ | ADT7410 | -55℃ から +150℃ まで測定できる温度センサです | ◯ | ◯ | ◯
I2C センサ | 温度, 圧力, 湿度 複合センサ | BME280 | 温度、湿度、気圧の測定ができる複合センサです | ◯ | ◯ | ◯
I2C センサ | 温度, 圧力 複合センサ | BMP180 | 温度と気圧の測定ができる複合センサです | ◯ | ◯ | ◯
I2C センサ | 温度, 圧力 複合センサ | BMP280 | 温度と気圧の測定ができる複合センサです(BMP180の後継品で精度が向上しています) | ◯ | ◯ | ◯
I2C センサ | 温湿度複合センサ | SHT30/31 | 温度と湿度の両方が測定可能なセンサ | ◯ | ◯ | ◯
I2C センサ | 温度, 湿度, 気圧, ガス 複合センサ | BME680 | 温度、湿度、気圧さらにガスが測れる複合センサです | ◯ | ◯ |  
I2C センサ | 非接触温度センサ | MLX90614 | 赤外線を利用した非接触型温度センサー | ◯ | ◯ | ◯
I2C センサ | 色センサ | TCS34725 | I2C接続の色センサー | ◯ | ◯ | ◯
I2C センサ | 距離(測距)センサ | GP2Y0E03 | センサから対象物までの距離を測定できるセンサです( 50cm 程度まで) | ◯ | ◯ | ◯
I2C センサ | レーザー距離センサ | VL53L0X | センサから対象物までの距離を測定できるセンサです( 2m 程度まで) | ◯ | ◯ | ◯
I2C センサ | レーザー距離センサ | VL53L1X | VL53L0Xより高出力長距離タイプ | ◯ | ◯ | ◯
I2C センサ | カラーセンサ | S11059 | RGB 各色と赤外線の強度を測定するセンサです | ◯ | ◯ |  
I2C センサ | 紫外線(UV)センサ | VEML6070 | 紫外線の強度を測定できるセンサです | ◯ | ◯ | ◯
I2C センサ | 3軸加速度+ジャイロ 複合センサ | MPU6050 | 3軸の加速度に加え、ジャイロの測定も可能な複合センサです | ◯ | ◯ | ◯
I2C センサ | 3軸加速度+ジャイロ+磁気 複合センサ | MPU9250 | 3軸の加速度、ジャイロのほか、磁気も測定可能な複合センサです | ◯ | ◯ | ◯
I2C センサ | 電流センサ | INA219 | 比較的大きなDC電流を測定するセンサ | ◯ | ◯ | ◯
I2C センサ | 近接・環境光・ジェスチャーセンサー | APDS9960 | 近接・環境光・ジェスチャーを読み取るセンサー | ◯ | ◯ |  
I2C センサ | 照度センサー | BH1750 | 照度センサー | ◯ | ◯ | ◯
I2C センサ | CO2+TVOCセンサ | CCS811 | 二酸化炭素（CO2）や金属酸化物（MOX）の含有量など、さまざまな揮発性有機化合物（TVOC）を検出 | ◯ | ◯ |  
I2C センサ | サーモグラフィ | AMG8833 | センサから見て上下左右のおよそ 60 度の範囲を 8x8 ピクセルに分割し、それぞれのエリアについて 0℃ ～ 80℃ の範囲で測定可能なサーモグラフィです | ◯ | ◯ | ◯
  | 有機ELディスプレイ | SSD1306 | I2C接続の小さなOLED（有機EL 128x64px）SSD1306ディスプレイへ文字を表示します。 |   |   | ◯
I2C センサ/Grove | Grove ジェスチャーセンサ | Grove-Gesture (PAJ7620U2) | 手を「上、下、左、右、遠ざかる、近づく、時計回り、反時計回り、手を振る」と動かしたときにそれらを検出するセンサです PAJ7620 | ◯ | ◯ | ◯
I2C センサ/Grove | Grove 光センサ | Grove-Light | 0.1lx から 40000lx まで測定可能な照度センサです | ◯ | ◯ |  
I2C センサ/Grove | Grobe タッチセンサ | Grove-Touch | 指などの接触を検出するセンサです MPR121 | ◯ | ◯ | ◯
I2C センサ/Grove | Grove 3軸加速度センサ | Grove-Accelerometer | 3軸の加速度を検出できるセンサです ADXL345 | ◯ | ◯ | ◯
I2C アクチュエータ/Grove | Grove 小型ディスプレイ | Grove-OledDisplay | 0.96inch、128x64dot の小型 OLED (有機 EL) ディスプレイです | ◯ | ◯ |  
I2C アクチュエータ/Grove | Neopixel LED |   | シンプルな配線の多数のLEDの発光を個々に制御できるフルカラーLED。8×8、円形、スティック型、テープ型など LED発光 | ◯ | ◯ | ◯
I2C アクチュエータ/Grove | サーボモーター ＋ PCA9685 |   | アームを指定した角度をに動かすことのできる部品 | ◯ | ◯ | ◯
  | ロードセル |   | 力（質量、トルク）を検出するセンサー。重さの検知などに |   | ◯ |  
GPIO | LED |   |   | ◯ | ◯ |  
GPIO | タクトスイッチ |   | ボタンを押している間だけ電気を流す部品 | ◯ | ◯ |  
GPIO | 赤外線人感センサ | KP-IR412 | 人体に反応するセンサです。感知距離：3m( 環境により前後) | ◯ | ◯ |  
GPIO | 赤外線人感センサ | HC-SR501 | 人体に反応するセンサです。およそ7m又は、低感度設定で3mまでの範囲内の動きを検出 | ◯ | ◯ |  
  | GPIO-HBridge |   | GPIO接続のH-BridgeモータドライバでDCモータの正転・逆転制御を可能にします。 |   |   |  
  |   |   |   |   |   |  
アナログセンサ | 感雨センサ | RD-4P | 雨(水)を検出するセンサです(GPIO) | ◯ |   |  
アナログセンサ | 水センサ | M-WL-J3Y | 水を検出するセンサです (利用にはI2C ADCが必要です) | ◯ |   |  
アナログセンサ | 圧力センサ | FSR 400 | 圧力が検知できるセンサです(利用にはI2C ADCが必要です) | ◯ |   |  
アナログセンサ | 土壌湿度センサ |   |   | × |   |  
アナログセンサ | 曲げセンサ |   |   | × |   |  
アナログセンサ | 心拍センサ |   |   | × |   |

**Comment by gurezo** [comment]
Google document
https://docs.google.com/spreadsheets/d/1iTIDHe9wqH_m_ck0TiM1JXA0OlGKVq1-VEkLnxdspz0/edit#gid=0

**Comment by gurezo** [comment]
タイトル変更
https://github.com/chirimen-oh/chirimen.org/issues/108

**Comment by gurezo** [comment]
一旦close
